@echo off
echo Setting up environment...
cd %~dp0
echo Checking dependencies...
C:\Users\herbert.camargo\Downloads\node-v24.0.0-win-x64\node.exe check-dependencies.js
echo Updating configuration...
C:\Users\herbert.camargo\Downloads\node-v24.0.0-win-x64\node.exe update-config.js
echo Starting server...
C:\Users\herbert.camargo\Downloads\node-v24.0.0-win-x64\node.exe start.js
pause 