@echo off
echo Setting up Node.js environment...
set PATH=%PATH%;C:\Users\herbert.camargo\Downloads\node-v24.0.0-win-x64
echo Installing dependencies...
C:\Users\herbert.camargo\Downloads\node-v24.0.0-win-x64\npm.cmd install
echo Starting Node.js server...
C:\Users\herbert.camargo\Downloads\node-v24.0.0-win-x64\node.exe server.js
pause 